export const cards = [
    { title: "AERIAL 1 - Noise", image: "/images/AERIAL 1 -Noise.png" },
    { title: "astro", image: "/images/astro.png" },
    { title: "completionist", image: "/images/completionist.png" },
    { title: "dilsay", image: "/images/dilsay.png" },
    { title: "ECT Vision app", image: "/images/ECT Vision app.png" },
    { title: "ECT Vision", image: "/images/ECT Vision.png" },
    { title: "encriptify (1)", image: "/images/encriptify (1).png" },
    { title: "encriptify", image: "/images/encriptify.png" },
    { title: "fundin bharat", image: "/images/fundin bharat.png" },
    { title: "garden vision app", image: "/images/garden vision app.png" },

    { title: "lubi", image: "/images/lubi.png" },
    { title: "Munna", image: "/images/Munna.png" },
    { title: "one rupee", image: "/images/one rupee.png" },
    { title: "p1", image: "/images/p1.png" },
    { title: "penalty kick", image: "/images/penalty kick.png" },
    { title: "red blood", image: "/images/red blood.png" },
    { title: "seat social partne", image: "/images/seat social partne.png" },
    { title: "six 30", image: "/images/six 30.png" },
    { title: "super over", image: "/images/super over.png" },
    { title: "swet social", image: "/images/swet social.png" },

    { title: "Tanera", image: "/images/Tanera.png" },
    { title: "teeto", image: "/images/teeto.png" },
    { title: "tire sensei", image: "/images/tire sensei.png" },
    { title: "token gamer", image: "/images/token gamer.png" },
    { title: "wax accound", image: "/images/wax accound.png" },
    { title: "zoop", image: "/images/zoop.png" },
];